server.port=8080
spring.application.name=spring-security6

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webst3;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=temporary8386@gmail.com
spring.mail.password=tcecsubzbzapmzxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=z4gdaoc9
cloudinary.api-key=638334192376662
cloudinary.api-secret=EwOm1iQNMkCN0zQiyzwhC3Dfunc

spring.main.allow-bean-definition-overriding=true